AREAS = [
    "Exterior",
    "Living Room",
    "Bedroom",
    "Kitchen",
    "Bathroom",
    "Other",
]

PROVINCES = [
    "ACEH", "SUMATERA UTARA", "SUMATERA BARAT", "RIAU",
    "KEPULAUAN RIAU", "JAMBI", "SUMATERA SELATAN",
    "KEPULAUAN BANGKA BELITUNG", "BENGKULU", "LAMPUNG",
    "DKI JAKARTA", "JAWA BARAT", "BANTEN", "JAWA TENGAH",
    "DI YOGYAKARTA", "JAWA TIMUR", "BALI",
    "NUSA TENGGARA BARAT", "NUSA TENGGARA TIMUR",
    "KALIMANTAN BARAT", "KALIMANTAN TENGAH",
    "KALIMANTAN SELATAN", "KALIMANTAN TIMUR",
    "KALIMANTAN UTARA", "SULAWESI UTARA", "GORONTALO",
    "SULAWESI TENGAH", "SULAWESI BARAT", "SULAWESI SELATAN",
    "SULAWESI TENGGARA", "MALUKU", "MALUKU UTARA",
    "PAPUA", "PAPUA BARAT", "PAPUA SELATAN",
    "PAPUA TENGAH", "PAPUA PEGUNUNGAN", "PAPUA BARAT DAYA",
]
